variables:
  GIT_SSL_NO_VERIFY: "1"

build:
  tags:
    - poc-kube
  stage: build
  image:
    name: pandoc/core:2.11.4
    entrypoint: ["/bin/sh", "-c"]
  script:
    - echo "running scripts in the build job"
