image: gitlab-registry.insee.fr/kubernetes/images/build/r-toolbox/onyxia-rstudio-insee:r4.2.1

stages:
  - check

variables:
  GIT_SSL_NO_VERIFY: "1"
  PKG_NAME: "rtauargus"

pkg_check:
  stage: check
  tags:
    - docker
  script:
    - Rscript -e 'devtools::check(check_dir = ".",
                                  error_on  = "error",
                                  cran      = FALSE,
                                  document  = FALSE,
                                  manual    = FALSE)'
  artifacts:
    paths:
      - "${PKG_NAME}_*.tar.gz"
