name: Coverage combine2ts

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest

    name: Coverage ${{ matrix.domain }}

    strategy:
      fail-fast: false
      matrix:
        domain: [ 'integer', 'character', 'double', 'logical', 'complex', 'raw', 'Date' ]

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 4.x  # Choisir la version R appropriée

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - name: renv status
        run: |
          options(repos = c(CRAN = "https://cloud.r-project.org"))
          renv::install("cpp11")
          renv::snapshot()
          renv::status()
        shell: Rscript {0}

      - name: Install covr
        run: install.packages("covr", repos = "https://cloud.r-project.org")
        shell: Rscript {0}

      - name: Move tests-combine2ts
        run: mv tests/testthat/tests-combine2ts/test-modify-combine2ts-${{ matrix.domain }} tests/testthat

      - name: Test coverage
        run: covr::codecov()
        shell: Rscript {0}

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
