name: Coverage simple

on:
  workflow_dispatch:
    inputs:
      Full coverage:
        description: 'Full coverage2 which will be triggered'
        required: true
        default: 'Full coverage'

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: 4.x  # Choisir la version R appropriée

    - name: Install dependencies
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        extra-packages: any::rcmdcheck
        needs: check

    - name: renv status
      run: |
        options(repos = c(CRAN = "https://cloud.r-project.org"))
        renv::install("cpp11")
        renv::snapshot()
        renv::status()
      shell: Rscript {0}

    - name: Generate coverage report
      run: |
        cov_report <- covr::file_coverage(source_files = list.files("./R", full.names = TRUE), test_files = "./tests/testthat/test-simple.R")
        covr::codecov(report = cov_report, token = Sys.getenv('CODECOV_TOKEN'))
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      shell: Rscript {0}

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
