# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  workflow_dispatch:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.os }}

    name: ${{ matrix.os }} (r ${{ matrix.r }})

    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest', 'windows-latest', 'macOS-latest' ]
        r: [ 'devel', 'release', 'oldrel-1', 'oldrel-2', 'oldrel-3' ]
        # r: [ 'devel', 'release', 'oldrel-1', 'oldrel-2', 'oldrel-3', '4.2.1', '4.1.1', '4.0.5', '3.6.1' ]
        # include:
        #   - http-user-agent: 'release'
        #     r: 'devel'
        # config:
          # - {os: macOS-latest,   r: 'release'}
          # - {os: windows-latest, r: 'release'}
          # - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release'}
          # - {os: windows-latest, r: 'release'}
          # - {os: ubuntu-latest,   r: 'oldrel-1'}
          # - {os: ubuntu-latest,   r: '3.6.1'}
          # - {os: ubuntu-latest,   r: '4.1.3'}
          # - {os: ubuntu-latest,   r: '4.1.1'}
          # - {os: ubuntu-latest,   r: '4.2.1'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v3

      - name: Set up Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r }}

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          args: '--as-cran'

