name: R Package Testing

on:
  workflow_dispatch:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    name: Testing ${{ matrix.domain }} on ${{ matrix.os }} (with r ${{ matrix.r }})

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        r: [ 'release', '4.2.1' ]
        domain: [ 'check', 'formatting', 'date_manipulation', 'conversion', 'libelles', 'modify' ]

    steps:

      - uses: actions/checkout@v3

      - name: Set up Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r }}
          # http-user-agent: ${{ matrix.http-user-agent }}
          # use-public-rspm: true

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - name: Install devtools
        run: install.packages("devtools", repos = "https://cloud.r-project.org")
        shell: Rscript {0}

      - name: Move tests-formatting
        run: mv tests/testthat/tests-${{ matrix.domain }}/* tests/testthat

      - name: Run tests
        run: devtools::test(stop_on_failure = TRUE)
        shell: Rscript {0}
