name: Check Other Tests

on:
  workflow_dispatch:

jobs:
  list-tests:
    name: List other_tests files
    runs-on: ubuntu-latest
    outputs:
      test-files: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List .R files in tests/coverage-Inf
        id: set-matrix
        run: |
          files=$(find tests/coverage-Inf -name "*.R" -type f | jq -R -s -c 'split("\n")[:-1]')
          echo "matrix=$files" >> "$GITHUB_OUTPUT"

  run-tests:
    name: Run ${{ matrix.test_file }}
    needs: list-tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test_file: ${{ fromJson(needs.list-tests.outputs.test-files) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          install.packages("testthat")
          # Ajoute d'autres packages nécessaires ici
        shell: Rscript {0}

      - name: Run specific test file
        run: |
          cat("Running: ", "${{ matrix.test_file }}", "\n")
          testthat::test_file("${{ matrix.test_file }}")
        shell: Rscript {0}
