name: Test coverage Inf

on: workflow_dispatch

jobs:
  list-tests:
    name: List other_tests files
    runs-on: ubuntu-latest
    outputs:
      test-files: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List .R files in tests/coverage-Inf
        id: set-matrix
        run: |
          files=$(find tests/coverage-Inf -type f -name "*.R")
          matrix=$(echo "$files" | jq -R -s -c 'split("\n")[:-1] | map({path: ., name: (. | split("/") | last)})')
          echo "matrix=$matrix" >> $GITHUB_OUTPUT

  run-tests:
    name: Run ${{ matrix.test.name }}
    needs: list-tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test: ${{ fromJson(needs.list-tests.outputs.test-files) }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - name: Run specific test file
        run: |
          devtools::load_all()
          cat("Running: ", "${{ matrix.test.path }}", "\n")
          testthat::test_file("${{ matrix.test.path }}", stop_on_failure = TRUE)
        shell: Rscript {0}
